version: '3.4'

services:
  colonymanager.webapi.host:
    image: ${DOCKER_REGISTRY-}colonymanagerwebapihost
    build:
      context: .
      dockerfile: ColonyManager.Api/src/ColonyManager.WebApi.Host/Dockerfile
    ports:
        - "8088:80" 
        - "8089:443"
    volumes: 
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
       - sql-server
       - seq-server

  seq-server:
    image: datalust/seq:latest
    hostname: seq-server
    container_name: seq-server
    ports:
        - "5341:5341"
        - "8081:80"
    environment:
        - ACCEPT_EULA=Y
    restart: unless-stopped
    volumes:
        - ./dockerVolumes/seq:/data 

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sql-server
    container_name: sql-server
    ports:
        - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Test123Test123
        - MSSQL_PID=Enterprise
        - TZ=Europe/Brussels 
    volumes:
        - ./dockerVolumes/mssql/data:/var/opt/mssql/data
        - ./dockerVolumes/mssql/logs:/var/opt/mssql/log
        - ./dockerVolumes/mssql/secrets:/var/opt/mssql/secrets
