name: .NET

on:
  push:
    branches: [ Developp ]
  pull_request:
    branches: [ Developp ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./ColonyManager.Api
    - name: Test
      run: dotnet test
      working-directory: ./ColonyManager.Api
